#:schema node_modules/wrangler/config-schema.json
name = "anteater-api_study-location-scraper"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
main = "src/handler.ts"
minify = true

[triggers]
crons = ["*/2 * * * *"]

[observability]
enabled = true

[[hyperdrive]]
binding = "DB"
id = "c498e76d4f68446ea55d0d92865257b5"
