name = "anteater-api"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "API_KEYS", id = "4c8dd3090bea4d469cd3c66b3002a5a2" },
  { binding = "GQL_CACHE", id = "4523675af51d41a4bd9b0b626ab958f9" },
]
workers_dev = false
route = { pattern = "anteaterapi.com", zone_name = "anteaterapi.com", custom_domain = true }
assets = { directory = "public" }

[vars]
CF_ENV = "prod"

[observability]
enabled = true

[[hyperdrive]]
binding = "DB"
id = "c498e76d4f68446ea55d0d92865257b5"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "DurableObjectRateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectRateLimiter"]
